language: julia
julia:
  - release
  - 0.3
  - 0.4
notifications:
    email: false
before_install:
    - sudo apt-get update
    - sudo apt-get install mysql-server mysql-client
    - sudo apt-get install libmyodbc unixodbc-bin
    - cat /etc/odbc.ini
    - find / -name 'lib*odbc*.so'
    - mysqladmin -u root -p version

script:
    - julia -e 'Pkg.add("HDF5"); Pkg.add("JLD")'
    - julia Pkg.test("ODBC")
