language: julia
julia:
  - release

notifications:
    email: false

services:
  - mysql

before_install:
  - mysql --version
  - sudo apt-get install libmyodbc libsqliteodbc unixodbc unixodbc-dev
  - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
  - sudo odbcinst -i -s -l -f ./test/odbc.ini

before_script:
    - julia -e 'Pkg.add("HDF5"); Pkg.add("JLD")'
