language: julia

os:
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

services:
  - mysql

before_install:
  - sudo apt-get update
  - sudo apt-get install unixodbc unixodbc-dev
  - curl https://dev.mysql.com/get/Downloads/Connector-ODBC/5.3/mysql-connector-odbc-5.3.6-linux-ubuntu12.04-x86-64bit.tar.gz > ~/myodbc.tar.gz
  - tar xvfz ~/myodbc.tar.gz -C ~/myodbc
  - sudo cp ~/myodbc/bin/* /usr/local/bin
  - sudo cp ~/myodbc/lib/* /usr/local/lib
  - myodbc-installer -a -d -n "MySQL ODBC 5.2 Driver" -t "Driver=/usr/local/lib/libmyodbc5w.so"

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("ODBC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("ODBC")); include(joinpath("docs", "make.jl"))'
