language: julia
julia:
  - release
  - 0.3
  - 0.4
notifications:
    email: false

services:
  - mysql

before_install:
  - mysql --version
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - sudo apt-get install libmyodbc libsqliteodbc unixodbc unixodbc-dev
  - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
  - sudo odbcinst -i -s -l -f ./test/mytest.odbc.ini

before_script:
    - julia -e 'Pkg.add("HDF5"); Pkg.add("JLD")'

after_failure:
    - julia -e 'using ODBC'
    - julia -e 'ODBC.connect("Default")'
