language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

services:
  - mysql

before_install:
  - sudo apt-get update
  - sudo apt-get install libmyodbc libsqliteodbc unixodbc unixodbc-dev
  - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
  - sudo odbcinst -i -s -l -f ./test/odbc.ini

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("ODBC", "test")); include("coverage.jl")'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("ODBC")); include(joinpath("docs", "make.jl"))'

after_success:
  - julia -e 'cd(Pkg.dir("ODBC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
