language: julia
julia:
  - release
  - 0.3
  - 0.4
notifications:
    email: false
before_install:
    - sudo apt-get update
    - sudo apt-get install mysql-server mysql-client
    - sudo apt-get install libmyodbc unixodbc-bin
    - sudo cat /etc/odbc.ini
    - sudo mysqladmin -u root -p version
    - sudo printf "\n[myodbc_mysql] \n Description = ODBC for MySQL \n Driver = /usr/lib/x86_64-linux-gnu/odbc/libmyodbc.so \n Setup = /usr/lib/x86_64-linux-gnu/odbc/libodbcmyS.so \n UsageCount = 1" >> /etc/odbcinst.ini
    - sudo printf "\n[Default] \n Description = DSN for MySQL \n Driver = myodbc_mysql \n Server = localhost \n Port = 3306 \n Socket = /var/run/mysqld/mysqld.sock \n Option = 3 \n ReadOnly = No \n USER = root \n PASSWORD =  \"\"" >> odbc.ini
    - sudo odbcinst -i -d -f /etc/odbcinst.ini
    - sudo odbcinst -i -s -l -f /etc/odbc.ini


script:
    - julia -e 'Pkg.add("HDF5"); Pkg.add("JLD")'
    - julia Pkg.test("ODBC")
